# Generated by Django 5.1 on 2024-08-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
